/**
 * The slice of Kestrel this repo uses, as the `kestrel` module (see kestrel/entry.ts). Hand
 * written against the pinned tag, and only as wide as the wrapper needs: the real
 * signatures live in vendor/kestrel and are checked by Kestrel's own typecheck.
 */

/** The bindings and vars Kestrel reads off `env` (its `AppEnv`), as the sandbox sets them. */
export interface KestrelEnv {
  DB: D1Database;
  MEDIA: R2Bucket;
  PROVIDER: string;
  APP_ORIGIN: string;
  ARCHIVE_BASE_PATH: string;
  SENDING_DOMAIN: string;
  FROM_ADDRESS: string;
  AWS_REGION: string;
  MIN_LEAD_SECONDS?: string;
  SUBREQUEST_BUDGET?: string;
}

/** Kestrel's resolved `Config`, opaque here: the wrapper only passes it back to Kestrel. */
export interface KestrelConfig {
  readonly appOrigin: string;
}

/** Kestrel's default export (src/index.ts). */
declare const kestrel: {
  fetch(request: Request, env: KestrelEnv, ctx: ExecutionContext): Promise<Response>;
  scheduled(controller: ScheduledController, env: KestrelEnv, ctx: ExecutionContext): Promise<void>;
};
export default kestrel;

/** src/env.ts: resolve and validate config from `env`; throws on config that would run wrong. */
export function getConfig(env: KestrelEnv): KestrelConfig;

/** An image the seed writes to R2, named `<bundle>/<file>` as in Kestrel's demo/posts. */
export interface DemoImageFile {
  bytes: ArrayBuffer;
  contentType: string;
  filename: string;
}

export interface SeedSummary {
  reset: true;
  subscribers: { confirmed: number; pending: number; unsubscribed: number };
  suppressions: number;
  audience: number;
  posts: { sent: number; scheduled: number; draft: number };
  deliveries: number;
  imagesWritten: number;
  logoWritten: boolean;
  urls: { archive: string[]; admin: string };
}

/** src/dev/seed.ts: reset the database and load the "Field Notes" demo publication. */
export function seedDatabase(
  env: KestrelEnv,
  config: KestrelConfig,
  imageFiles?: DemoImageFile[],
  logoFile?: { bytes: ArrayBuffer; contentType: string },
): Promise<SeedSummary>;

/** src/generated/version.ts: the build stamp. */
export const BUILD_INFO: {
  version: string;
  sha: string;
  tag: string;
  buildTime: string;
  repoUrl: string;
};

/** vendor/demo-assets.ts, generated by scripts/fetch-kestrel.mjs. */
export const demoImages: DemoImageFile[];
export const demoLogo: { bytes: ArrayBuffer; contentType: string } | undefined;
/** Kestrel's migrations/*.sql, in name order. */
export const migrations: { name: string; sql: string }[];
